<div class="row">
    <table>
        <tr>
            <td>Model:</td>
            <td>{model}</td>
        </tr>
        <tr>
            <td>Manufactuer:</td>
            <td>{manufacturer}</td>
        </tr>
        <tr>
            <td>Price:</td>
            <td>${price}</td>
        </tr>
        <tr>
            <td>Seats:</td>
            <td>{seats}</td>
        </tr>
        <tr>
            <td>Reach:</td>
            <td>{reach}</td>
        </tr>
        <tr>
            <td>Cruise:</td>
            <td>{cruise}</td>
        </tr>
        <tr>
            <td>Takeoff:</td>
            <td>{takeoff}</td>
        </tr>
        <tr>
            <td>Hourly:</td>
            <td>{hourly}</td>
        </tr>
    </table>
</div>
